phpfpm:
  container_name: php_workshop
  image: bykclk/php-symfony
  tty: true
  volumes:
    - /var/www/:/var/www
    - ./php.ini:/usr/local/etc/php/php.ini
    - ./php-fpm.conf:/user/local/etc/php-fpm.d/www.conf
  volumes_from:
    - data
  links:
    - mysql
nginx:
  container_name: nginx_workshop
  image: nginx
  volumes_from:
    - data
  volumes:
    - /var/www/:/var/www
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-servers:/etc/nginx/servers
  ports:
    - "80:80"
  links:
    - phpfpm
mysql:
  container_name: mysql_workshop
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: symfony
    MYSQL_USER: symfony
    MYSQL_DATABASE: symfony
  ports:
    - 3306:3306 
data:
  container_name: busybox_workshop
  image: busybox
  volumes:
    - /var/lib/mysql/data
  tty: true
  stdin_open: true
